Repository unicode-org/cldr, pull requests merged in 2021-05, with the labels that each got.

#1245 CLDR-14555 addXpaths needs to not use autocommit conn
  tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
Labels: fails-smoketest

#1258 CLDR-14757 ci: temporarily ignore 'vagrant up' failures
  .github/workflows/ansible-lint.yml
Labels: bug

#1226 CLDR-14584 keyboard elements structure
  docs/ldml/tr35-keyboards.md
Labels: keyboard
